server:
  port:
    8083

spring:
  profiles:
    active: dev_per
  application:
    name: IPO-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: pass@word1
    url: jdbc:mysql://localhost:3306/stockdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  profiles: dev_per
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: abcd
    url: jdbc:mysql://localhost:3306/stockdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true