server:
  port:
    8088

spring:
  profiles:
    active: dev_mongo
  application:
    name: COMPANY-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registery: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: pass@word1
    url: jdbc:mysql://localhost:3306/stockdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  profiles: dev_per
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: abcd
    url: jdbc:mysql://localhost:3306/stockdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---

spring:
  profiles: dev_mongo
  data:
    mongodb:
      uri: mongodb+srv://mohit:abcd@cluster0.lre69.mongodb.net/stockmdb
      database: stockmdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false